language: node_js

notifications:
  slack: generaptr:WVInkDTeAegbpm2wBcMmCKv2
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a80c735c20f7603bf06a
    on_success: change  
    on_failure: always  
    on_start: never     

node_js:
  - "7.5"

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE test;'
  - mysql -u root test < ./test/handlers/mysql/data.sql

script:
  - typings install
  - npm run lint
  - npm run compile
  - npm run test:coverage

after_success:
  - npm run coveralls
  - rm -rf ./raml.test

deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_TOKEN
  on:
    branch: develop